# Generated by Django 4.2 on 2026-02-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('cn', 'Chineese')], default='en', max_length=10, verbose_name='preferred language'),
        ),
    ]
