# Generated by Django 6.0 on 2026-03-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_user_referral_code_user_referral_reward_claimed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('cn', 'Chineese'), ('zh', 'Chineese')], default='en', max_length=10, verbose_name='preferred language'),
        ),
    ]
