# Generated by Django 6.0 on 2026-04-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_deliveryboyprofile_and_role_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
    ]
