# Generated by Django 6.0 on 2026-04-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_useraddress_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ar', 'Arabic'), ('cn', 'Chineese'), ('zh', 'Chineese')], max_length=10, null=True, verbose_name='preferred language'),
        ),
    ]
