# Generated by Django 6.0 on 2026-04-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='smsmessage',
            new_name='SMS_smsmess_recipie_636b12_idx',
            old_name='SMS_smsmess_recipi_idx',
        ),
        migrations.RenameIndex(
            model_name='smsmessage',
            new_name='SMS_smsmess_templat_d85f2b_idx',
            old_name='SMS_smsmess_templ_status_idx',
        ),
        migrations.RenameIndex(
            model_name='smsmessage',
            new_name='SMS_smsmess_created_81c7a2_idx',
            old_name='SMS_smsmess_create_idx',
        ),
        migrations.RenameIndex(
            model_name='smstemplate',
            new_name='SMS_smstemp_templat_1b2828_idx',
            old_name='SMS_smstem_templa_idx',
        ),
        migrations.RenameIndex(
            model_name='smstemplate',
            new_name='SMS_smstemp_approva_7b41de_idx',
            old_name='SMS_smstem_approv_idx',
        ),
        migrations.RenameIndex(
            model_name='smstemplate',
            new_name='SMS_smstemp_sms_typ_219a88_idx',
            old_name='SMS_smstem_sms_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='smswebhooklog',
            new_name='SMS_smswebh_event_t_8ad192_idx',
            old_name='SMS_smswebb_event_idx',
        ),
    ]
