# Generated by Django 6.0.2 on 2026-02-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('key', models.CharField(db_index=True, help_text="Logical key, e.g. 'home_top_banner', 'festival_popup'", max_length=100, verbose_name='key')),
                ('position', models.CharField(choices=[('home_banner', 'Home Banner'), ('category_banner', 'Category Banner'), ('popup', 'Popup'), ('announcement', 'Announcement')], default='home_banner', max_length=50, verbose_name='position')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='subtitle')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image_mobile', models.ImageField(blank=True, help_text='Smaller image optimized for phones and small screens.', null=True, upload_to='marketing/mobile/', verbose_name='mobile image')),
                ('image_desktop', models.ImageField(blank=True, help_text='Larger image for tablets/desktop.', null=True, upload_to='marketing/desktop/', verbose_name='desktop image')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='start at')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='end at')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'Marketing Media',
                'verbose_name_plural': 'Marketing Media',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
