# Generated by Django 5.2.3 on 2026-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmedia',
            name='cta',
            field=models.CharField(blank=True, help_text="Call-to-action text or link (e.g. 'Shop Now', 'Learn More', '/products/sale')", max_length=255, verbose_name='call to action'),
        ),
        migrations.AddField(
            model_name='marketingmedia',
            name='highlight',
            field=models.BooleanField(default=False, help_text='Mark as highlighted to feature prominently', verbose_name='highlight'),
        ),
        migrations.AddField(
            model_name='marketingmedia',
            name='tag',
            field=models.CharField(blank=True, help_text="Tag for categorizing/filtering media (e.g. 'summer', 'sale', 'new')", max_length=100, verbose_name='tag'),
        ),
    ]
