# Generated by Django 5.2.3 on 2026-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0003_marketingmedia_cta_marketingmedia_highlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmedia',
            name='highlight',
            field=models.TextField(blank=True, help_text='Highlight text or badge to display on media', verbose_name='highlight'),
        ),
    ]
