# Generated by Django 6.0 on 2026-04-03 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0004_alter_marketingmedia_highlight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_order_discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('first_order_discount_value', models.DecimalField(decimal_places=2, default=10.0, help_text='First order discount percentage or fixed amount', max_digits=10)),
                ('first_order_min_amount', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum order amount to use first order coupon', max_digits=10)),
                ('first_order_validity_days', models.PositiveIntegerField(default=30, help_text='Days from account creation when first order coupon is valid')),
                ('referral_discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('referral_discount_value', models.DecimalField(decimal_places=2, default=15.0, help_text='Referral reward discount percentage or fixed amount', max_digits=10)),
                ('referral_min_amount', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum order amount to use referral coupon', max_digits=10)),
                ('referral_validity_days', models.PositiveIntegerField(default=60, help_text='Days from referral when referral coupon is valid')),
                ('referral_usage_limit', models.PositiveIntegerField(default=1, help_text='How many times each referral coupon can be used')),
                ('referrer_discount_value', models.DecimalField(decimal_places=2, default=15.0, help_text='Discount given to referrer for successful referral', max_digits=10)),
                ('referrer_validity_days', models.PositiveIntegerField(default=60, help_text='Days from referral when referrer coupon is valid')),
                ('max_discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount cap for percentage-based coupons', max_digits=10, null=True)),
                ('is_referral_active', models.BooleanField(default=True, help_text='Enable/disable referral rewards system')),
                ('is_first_order_active', models.BooleanField(default=True, help_text='Enable/disable first order rewards')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward Configuration',
                'verbose_name_plural': 'Reward Configuration',
            },
        ),
    ]
