# Generated by Django 6.0.2 on 2026-02-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_response',
            field=models.TextField(blank=True, null=True, verbose_name='admin response'),
        ),
    ]
