# Generated by Django 6.0 on 2026-03-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_review_admin_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Admins can uncheck this to hide the review', verbose_name='is visible'),
        ),
    ]
