# Generated by Django 6.0 on 2026-04-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='WhatsApp_wh_recipie_062be8_idx',
            old_name='WhatsApp_wh_recipi_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='WhatsApp_wh_templat_141e35_idx',
            old_name='WhatsApp_wh_templ_status_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='WhatsApp_wh_created_629fb5_idx',
            old_name='WhatsApp_wh_create_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsapptemplate',
            new_name='WhatsApp_wh_templat_8483f5_idx',
            old_name='WhatsApp_wh_templa_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsapptemplate',
            new_name='WhatsApp_wh_approva_319bf2_idx',
            old_name='WhatsApp_wh_approv_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsapptemplate',
            new_name='WhatsApp_wh_integra_02aa3b_idx',
            old_name='WhatsApp_wh_integr_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappwebhooklog',
            new_name='WhatsApp_wh_event_t_f7161b_idx',
            old_name='WhatsApp_wh_event_idx',
        ),
    ]
