# Generated by Django 6.0 on 2026-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsApp', '0002_rename_whatsapp_wh_recipi_idx_whatsapp_wh_recipie_062be8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='buttons',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
