# Generated by Django 6.0 on 2026-04-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
        ('Products', '0011_productpreparationspecification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='preparation_instructions',
            field=models.TextField(blank=True, help_text='Optional customer instructions for the selected preparation.', verbose_name='preparation instructions'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='preparation_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='Products.productpreparationspecification', verbose_name='preparation specification'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='Cart_cartit_cart_id_9edaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'preparation_specification'], name='Cart_cartit_cart_id_5996b1_idx'),
        ),
    ]
