# Generated by Django 6.0.2 on 2026-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True, verbose_name='delivery notes'),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='preferred delivery date'),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_delivery_slot',
            field=models.CharField(blank=True, help_text='e.g., 9AM - 12PM, 2PM - 5PM', max_length=50, null=True, verbose_name='preferred delivery slot'),
        ),
    ]
