# Generated by Django 4.2 on 2026-02-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order_delivery_notes_order_preferred_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('TELR', 'Telr / Card'), ('COD', 'Cash on Delivery')], default='TELR', max_length=50, verbose_name='payment method'),
        ),
    ]
