# Generated by Django 5.2.3 on 2026-03-29 15:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0004_alter_marketingmedia_highlight'),
        ('Orders', '0004_order_tip_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Marketing.coupon', verbose_name='coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='coupon code'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='delivery charge'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='discount amount'),
        ),
        migrations.CreateModel(
            name='DeliveryChargeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_free_shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Orders >= this amount get free shipping. Default: AED 40', max_digits=10, verbose_name='minimum amount for free shipping')),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Delivery charge for orders below min_free_shipping_amount. Default: AED 10', max_digits=10, verbose_name='delivery charge')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable delivery charges', verbose_name='is active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Charge Configuration',
                'verbose_name_plural': 'Delivery Charge Configuration',
            },
        ),
    ]
