# Generated by Django 6.0 on 2026-04-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_order_coupon_order_coupon_code_order_delivery_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='telr_reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='ziina_payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ziina Payment Intent ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ZIINA', 'Ziina / Card'), ('COD', 'Cash on Delivery')], default='ZIINA', max_length=50, verbose_name='payment method'),
        ),
    ]
