# Generated by Django 6.0 on 2026-04-12 10:29

import django.db.models.deletion
from django.db import migrations, models


def clear_old_slot_text(apps, schema_editor):
    """Clear existing text values in preferred_delivery_slot before converting to FK."""
    Order = apps.get_model('Orders', 'Order')
    Order.objects.exclude(preferred_delivery_slot__isnull=True).update(preferred_delivery_slot=None)


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_delivery_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Morning Slot', '8 AM - 9 AM'", max_length=100, verbose_name='slot name')),
                ('start_time', models.TimeField(help_text='Slot starts at (e.g. 08:00)', verbose_name='start time')),
                ('end_time', models.TimeField(help_text='Slot ends at (e.g. 09:00)', verbose_name='end time')),
                ('cutoff_time', models.TimeField(help_text='Orders must be placed before this time (same day) to select this slot. e.g. 07:30', verbose_name='cutoff time')),
                ('is_active', models.BooleanField(default=True, help_text='Globally enable/disable this slot', verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Time Slot',
                'verbose_name_plural': 'Delivery Time Slots',
                'ordering': ['sort_order', 'start_time'],
            },
        ),
        # Clear old text values before converting to FK
        migrations.RunPython(clear_old_slot_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='preferred_delivery_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Orders.deliverytimeslot', verbose_name='preferred delivery slot'),
        ),
        migrations.CreateModel(
            name='DeliverySlotOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('is_active', models.BooleanField(default=False, help_text='Set to False to disable this slot on this specific date', verbose_name='is active')),
                ('reason', models.CharField(blank=True, help_text='Optional reason for override', max_length=255, verbose_name='reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='Orders.deliverytimeslot', verbose_name='delivery time slot')),
            ],
            options={
                'verbose_name': 'Delivery Slot Override',
                'verbose_name_plural': 'Delivery Slot Overrides',
                'ordering': ['date', 'slot__sort_order'],
                'unique_together': {('slot', 'date')},
            },
        ),
    ]
