# Generated by Django 6.0 on 2026-04-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_deliverytimeslot_alter_order_preferred_delivery_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='refund ID'),
        ),
    ]
