# Generated by Django 6.0 on 2026-04-26 11:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_add_refund_id_to_payment'),
        ('Products', '0011_productpreparationspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='preparation_extra_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra price for this preparation method at order time', max_digits=10, verbose_name='preparation extra price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_instructions',
            field=models.TextField(blank=True, help_text='Additional custom instructions provided by the user', null=True, verbose_name='preparation instructions'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_specification',
            field=models.ForeignKey(blank=True, help_text='Selected preparation method for this product', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='Products.productpreparationspecification', verbose_name='preparation specification'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_specification_name',
            field=models.CharField(blank=True, help_text='Snapshot of the preparation spec name at order time', max_length=255, verbose_name='preparation specification name'),
        ),
    ]
