# Generated by Django 6.0.2 on 2026-02-12 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='template name')),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App Notification')], max_length=20, verbose_name='type')),
                ('subject', models.CharField(blank=True, help_text='Subject for Email/Push', max_length=255, verbose_name='subject')),
                ('body', models.TextField(help_text='Content. Use {{ user.first_name }} for dynamic values.', verbose_name='body')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App Notification')], default='IN_APP', max_length=20, verbose_name='type')),
                ('send_to_all', models.BooleanField(default=False, verbose_name='send to all users')),
                ('is_sent', models.BooleanField(default=False, verbose_name='is sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('recipients', models.ManyToManyField(blank=True, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast Message',
                'verbose_name_plural': 'Broadcast Messages',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('action_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='action URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
