# Generated by Django 6.0.2 on 2026-02-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='Notifications.notificationtemplate'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
    ]
