# Generated by Django 6.0 on 2026-03-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='message'),
        ),
    ]
