# Generated by Django 6.0.2 on 2026-02-12 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='products/videos/', verbose_name='video file')),
                ('video_url', models.URLField(blank=True, help_text='Link to YouTube, Vimeo, etc.', null=True, verbose_name='video URL')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product Video',
                'verbose_name_plural': 'Product Videos',
            },
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
