# Generated by Django 6.0.2 on 2026-02-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_product_brand_productvideo_delete_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expected_delivery_time',
            field=models.CharField(blank=True, help_text="e.g., '30-60 mins', 'Next Day', '2-3 Business Days'", max_length=100, null=True, verbose_name='expected delivery time'),
        ),
    ]
