# Generated by Django 6.0 on 2026-03-03 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_expected_delivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDeliveryTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimum quantity for this tier to apply', verbose_name='minimum quantity')),
                ('delivery_days', models.PositiveIntegerField(help_text='Number of days required for delivery for this quantity range', verbose_name='delivery days')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tiers', to='Products.product')),
            ],
            options={
                'verbose_name': 'Delivery Tier',
                'verbose_name_plural': 'Delivery Tiers',
                'ordering': ['min_quantity'],
                'unique_together': {('product', 'min_quantity')},
            },
        ),
    ]
