# Generated by Django 6.0 on 2026-03-05 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_productdeliverytier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimum quantity for this discount to apply', verbose_name='minimum quantity')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Percentage discount (0-100) for this quantity range', max_digits=5, verbose_name='discount percentage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_tiers', to='Products.product')),
            ],
            options={
                'verbose_name': 'Discount Tier',
                'verbose_name_plural': 'Discount Tiers',
                'ordering': ['min_quantity'],
                'unique_together': {('product', 'min_quantity')},
            },
        ),
    ]
