# Generated by Django 6.0 on 2026-03-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_productdiscounttier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kg'), ('packet', 'Packet')], default='piece', max_length=20, verbose_name='unit'),
        ),
    ]
