# Generated by Django 6.0 on 2026-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kg'), ('Gram', 'g')], default='piece', max_length=20, verbose_name='unit'),
        ),
    ]
