# Generated by Django 6.0 on 2026-03-28 10:14

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_emirates',
            field=models.JSONField(default=Products.models.default_available_emirates, verbose_name='available emirates'),
        ),
    ]
