# Generated by Django 6.0 on 2026-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_productnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_arabic',
            field=models.CharField(blank=True, max_length=100, verbose_name='name arabic'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_chinese',
            field=models.CharField(blank=True, max_length=100, verbose_name='name chinese'),
        ),
    ]
