# Generated by Django 6.0 on 2026-05-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_add_name_arabic_name_chinese_to_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
