# Generated by Django 6.0 on 2026-04-26 11:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_add_name_arabic_name_chinese_to_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPreparationSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Live (Packed in Air bag)' or 'Whole cleaned headon'", max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Additional details about this preparation method', verbose_name='description')),
                ('image', models.ImageField(blank=True, help_text='Visual representation of this preparation option', null=True, upload_to='preparation_specs/', verbose_name='image')),
                ('extra_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional cost for this preparation method (in AED)', max_digits=10, verbose_name='extra price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_specifications', to='Products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product Preparation Specification',
                'verbose_name_plural': 'Product Preparation Specifications',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='Products_pr_product_e26dcf_idx')],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
