# Generated by Django 6.0 on 2026-05-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_productpreparationspecification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
