# Generated by Django 6.0 on 2026-05-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_category_options'),
        ('Products', '0012_alter_category_options'),
    ]

    operations = [
    ]
