# Generated by Django 6.0 on 2026-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_merge_20260525_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kg'), ('100 Gram', '100 Gram')], default='piece', max_length=20, verbose_name='unit'),
        ),
    ]
