# Generated by Django 6.0 on 2026-07-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_productunit_product_unit_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sortorder', 'id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='sortorder',
            field=models.PositiveIntegerField(default=1, help_text='Display order for products. Multiple products can have the same order.', verbose_name='sort order'),
        ),
    ]
